# Generated by Django 2.1.7 on 2019-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(choices=[('O', 'Operations'), ('F', 'Finance'), ('H', 'HR'), ('M', 'Marketing'), ('R', 'R & D')], default='O', max_length=1)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
